name: stylish
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  flutter_bloc: ^9.1.1
  google_maps_flutter: ^2.6.0
  geocoding: ^2.2.0
  geolocator: ^10.1.0

  # localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.2.1
  dio: ^5.9.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/splach_logo.png
  min_sdk_android: 21
